In [1]:
import numpy as np

In [4]:
from numpy import uint8

_A = [[1,2,3],[4,5,6]] #it's just a list

A = np.array(_A, dtype=uint8) #create a numpy array from list

print("_A: ",_A)
print("A: ", A)
print(type(A))

_A:  [[1, 2, 3], [4, 5, 6]]
A:  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
print("A[0,1] =", A[0,1]) #value at row 0, colunm 1
print("A[:,1] =", A[:,1]) #values at all row, colunm 1
print("A[0,:] =", A[0,:]) #values at row 0, all colunm

A[0,1] = 2
A[:,1] = [2 5]
A[0,:] = [1 2 3]


In [11]:
_B = [7,8,9]
B = np.array(_B, dtype= uint8)

print("A*B =", A.dot(B)) #or
print("A*B =", A@B)

A*B = [ 50 122]
A*B = [ 50 122]


In [14]:
A_1 = [[1,2,3],[10,20,30]]
A_1 = np.array(A_1, dtype=uint8)
print("A*A_1 =", A*A_1) #elemnt-wise

A*A_1 = [[  1   4   9]
 [ 40 100 180]]


In [12]:
c = np.eye(3) #identify matrix
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
m = [[1,2,1], [4,3,1], [5,2,4]]
m = np.array(m, dtype=uint8)
print(m == 1)
print(m != 1)

[[ True False  True]
 [False False  True]
 [False False False]]
[[False  True False]
 [ True  True False]
 [ True  True  True]]


In [21]:
m_inv = np.linalg.pinv(A) #create inverse matrix
print(m_inv)

[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [22]:
m_tp = np.transpose(m) #transpose matrix
print(m_tp)

[[1 4 5]
 [2 3 2]
 [1 1 4]]


In [25]:
print(np.size(A,0)) #number of row
print(np.size(A,1)) #number of colunm


2
3
